urls = {
    '49ers': 'https://www.49ers.com/team/players-roster/',
    'bears': 'https://www.chicagobears.com/team/players-roster/',
    'bengals': 'https://www.bengals.com/team/players-roster/' ,
    'bills': 'https://www.buffalobills.com/team/players-roster/',
    'broncos': 'https://www.denverbroncos.com/team/players-roster/',
    'browns': 'https://www.clevelandbrowns.com/team/players-roster/',
    'buccaneers': 'https://www.buccaneers.com/team/players-roster/',
    'cardinals': 'https://www.azcardinals.com/team/players-roster/',
    'chargers': 'https://www.chargers.com/team/players-roster/',
    'chiefs': 'https://www.chiefs.com/team/players-roster/',
    'colts': 'https://www.colts.com/team/players-roster/',
    'cowboys': 'https://www.dallascowboys.com/team/players-roster/',
    'dolphins': 'https://www.miamidolphins.com/team/players-roster/',
    'eagles': 'https://www.philadelphiaeagles.com/team/players-roster/',
    'falcons': 'https://www.atlantafalcons.com/team/players-roster/',
    "giants": 'https://www.giants.com/team/players-roster/',
    'jaguars': 'https://www.jaguars.com/team/players-roster/',
    'jets': 'https://www.newyorkjets.com/team/players-roster/',
    'lions': 'https://www.detroitlions.com/team/players-roster/',
    'packers': 'https://www.packers.com/team/players-roster/',
    'panthers': 'https://www.panthers.com/team/players-roster/',
    'patriots': 'https://www.patriots.com/team/players-roster/',
    'raiders': 'https://www.raiders.com/team/players-roster/',
    'rams': 'https://www.therams.com/team/players-roster/',
    'ravens': 'https://www.baltimoreravens.com/team/players-roster/',
    'redskins': 'https://www.redskins.com/team/players-roster/',
    'seahawks': 'https://www.seahawks.com/team/players-roster/',
    'steelers': 'https://www.steelers.com/team/players-roster/',
    'texans': 'https://www.houstontexans.com/team/players-roster/',
    'titans': 'https://www.titansonline.com/team/players-roster/',
    'vikings': 'https://www.vikings.com/team/players-roster/',
        }

